DELIMITER $$
DROP PROCEDURE IF EXISTS Create_role_table $$
CREATE PROCEDURE Create_role_table()
BEGIN
	START TRANSACTION;

CREATE TABLE IF NOT EXISTS Band (
	Id INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(64) NOT NULL,
	Level TINYINT NOT NULL
);

END $$
DELIMITER ;
CALL Create_role_table();