INSERT INTO JobRole (`Name`, `Description`, `SharePointLink`, `BandId`, `CapabilityId`) VALUES
('Techssnology Lesdfsdfader', 'Responsible for leading technology initiatives and teams within the organization.', 'https://example.com/techleader', 1, 1),
('Principal', 'A high-level position with significant responsibilities in the organization.', 'https://example.com/principal', 2, 1),
('Principal Architect', 'Responsible for designing and overseeing architectural solutions.', 'https://example.com/principalarchitect', 3, 1 ),
('Principal Test Architect', 'Responsible for designing and managing test architecture.', 'https://example.com/principaltestarchitect', 1, 2),
('Manager', 'Manages a team or department within the organization.', 'https://example.com/manager', 5, 3),
('Dynamics 365 / Power Platform Solution Architect', 'Designs solutions using Dynamics 365 and Power Platform.', 'https://example.com/dynamicsarchitect', 6, 3),
('Solution Architect', 'Designs comprehensive solutions for various business challenges.', 'https://example.com/solutionarchitect', 7, 2),
('Test Architect', 'Designs and oversees testing strategies and architecture.', 'https://example.com/testarchitect', 8, 2),
('Intelligent Automation Solution Architect', 'Designs solutions for intelligent automation and AI-driven processes.', 'https://example.com/automationarchitect', 9, 3),
('Consultant', 'Provides expert advice and consulting services to clients or teams.', 'https://example.com/consultant', 6, 3),
('Innovation Lead', 'Leads innovation efforts and fosters a culture of creativity.', 'https://example.com/innovationlead', 5, 2),
('Lead Software Engineer', 'Leads software development teams and projects.', 'https://example.com/leadsoftwareengineer', 4, 2),
('Lead Managed Services Engineer', 'Leads teams responsible for managed IT services.', 'https://example.com/managedservicesengineer', 3, 2),
('Technical Architect', 'Designs and oversees technical solutions and architecture.', 'https://example.com/technicalarchitect', 4, 2),
('Lead Test Engineer', 'Leads testing teams and ensures quality assurance.', 'https://example.com/leadtestengineer', 5, 2),
('Lead NFT Engineer', 'Leads teams focused on non-functional testing.', 'https://example.com/leadnftengineer', 3, 4),
('Test Manager', 'Manages testing teams and strategies.', 'https://example.com/testmanager', 2, 4),
('Lead Product Specialist', 'Leads product-related initiatives and teams.', 'https://example.com/leadproductspecialist', 1, 4),
('Senior Associate', 'A senior-level position with significant experience and responsibilities.', 'https://example.com/seniorassociate', 2, 3),
('Senior Software Engineer', 'Experienced software developer with a senior role.', 'https://example.com/seniorsoftwareengineer', 3, 1),
('Senior Front-End Engineer', 'Experienced front-end developer with senior responsibilities.', 'https://example.com/seniorfrontendengineer', 4, 2),
('Senior Support Technician', 'Provides senior-level support and troubleshooting services.', 'https://example.com/seniorsupporttechnician', 5, 3),
('Senior Test Engineer', 'Experienced test engineer with senior responsibilities.', 'https://example.com/seniortestengineer', 6, 4);